### ISSUE TITLE
Pass parent doc as parameter when calling getDoc for children

### ISSUE THREAD

**Issue by jkuester** [latin-panda/test-data-generator#2]
It is pretty common in the CHT data-structure to de-normalize data from parent contacts down to their child contacts and reports.  (E.g. you may want to record the name of a patient as part of the report data.)  

I could be possible to support loading this kind of data by adding a parameter to the `DesignSpec.getDoc()` function that would be the parent doc.  Then logic for creating the new doc could use data from the parent!

**Comment by latin-panda** [comment]
Tatiana mentioned something similar: Fetching existing contacts to access their name and other attributes; then, we can associate these values to the report's fields. 

To illustrate this:
```
export default (context) => {
  const existingContact = await fetchExistingContact(contactUUID);
  return [
    {
      amount: 1,
      getDoc: () => getPregnancyDangerSign(existingContact),
    }
 ......
 ......

const getPregnancyDangerSign = (existingContact) => {
  return {
    form: 'pregnancy_danger_sign',
    fields: {
      patient_age_in_years: existingContact.age, // <<----- 
      patient_name: existingContact.name, // <<----- 
```

Is this what you mean, but pass the doc as a parameter instead of a request to keep it synchronous?

**Comment by jkuester** [comment]
Right, exactly!  Seems like just passing the parent doc as a param might be sufficient for at least the 80% most common use cases and it would still be simple to implement in the code and consume when writing designs....

**Comment by latin-panda** [comment]
On this 🔨
