### ISSUE TITLE
Add a way to create 10k+ users with telemetry docs

### ISSUE THREAD

**Issue by mrjones-plip** [latin-panda/test-data-generator#6]
There's been a [couple](https://github.com/medic/cht-core/issues/8462#issuecomment-1899796948) [times](https://github.com/medic/cht-core/issues/8689) when we've needed to do performance testing of a new CHT branch/PR and it needs 10k+ users with telemetry docs from being "active" for months (years!) in a realistic hierarchy. The current way to do this to clone a CHT DB from a production instance. 

it would be super duper great if the test data tool could do this instead!

**Comment by jkuester** [comment]
@mrjones-plip just for clarification, what do you mean by "tall hierarchy"?

**Comment by mrjones-plip** [comment]
hah! fair question.  

I'd say "configurable hierarchy" would be more accurate than "tall".  In the two instances I cited ([this](https://github.com/medic/cht-core/issues/8462#issuecomment-1899796948) and [ths](https://github.com/medic/cht-core/issues/8689)) I needed more than just a 3 level hierarchy with and more than the single place at each level I quickly created by hand.  

Being able to configure this to be say 5 levels with 100s of places at each level would be great. This would mean I could end up with a realistic hierarchical distributions of ~10k places that I could easily attach ~10k contacts to, and in turn ~10k users attached to those contacts (and then 100s of telemetry docs per user for >1m docs total!)

**Comment by jkuester** [comment]
Maybe I am missing something here, but I think this tool already supports writing configurable hierarchy.  Really you can nest contacts as deep as you want (and in whatever order).

**Comment by mrjones-plip** [comment]
ah! no - it is **_I_** who is missing something - that the tool can already supports writing configurable hierarchy - sorry!

I'll update the title and body.

**Comment by latin-panda** [comment]
Thanks for opening the issue @mrjones-plip! 
@jkuester fixed the issue and it's available in the [latest release ](https://github.com/latin-panda/test-data-generator/releases/tag/v0.1.0) 

There is a little fix to associate an existing contact to reports correctly in >3 levels hierarchy. I opened a [PR](https://github.com/latin-panda/test-data-generator/pull/10) (#9) Ready for review.  

We still need to improve the samples in this repo, if you happen to make telemetry docs for `default` config. It would be really helpful if you could open a PR and add it as a new sample file, `add-telemetry-records.js` in the [sample folder](https://github.com/latin-panda/test-data-generator/tree/main/sample-designs).

**Comment by latin-panda** [comment]
@mrjones-plip It's possible to hit a rate limit with this tool if inserting a deep hierarchy, for example, if you are designing data like this.

```
[ 
  { 
    amount: 40,
    getDoc: () => hospitalDoc,
    children: [
        { 
            amount: 60,
            getDoc: () => areaDoc,
            children: [
                { 
                     amount: 80,
                     getDoc: () => wardDoc,
                }
            ]
        }
     ]
  }
]
```

It will make the following requests to CouchDB:
- 1 to create hospitals
- 40 to create areas
- 40 * 60 to create wards

Maybe we can implement a "wait" mechanism to avoid the rate limit. 
At the moment, what I'm doing to avoid that problem is just setting the 'amount' smaller and rerunning the script manually, which gives enough time between requests. ([issue](https://github.com/latin-panda/test-data-generator/issues/12))

I've also improve the error handling to help track errors easier, [the PR is ready](https://github.com/latin-panda/test-data-generator/pull/8)
